### ISSUE TITLE
add sign in and sign up component

### ISSUE THREAD

**Issue by yoonlight** [kw-kwix/html-mediapipe#14]
## Todo

- [x] add to HTML component
- [x] connect to Firebase
- [x] sign in and sign up test
- [x] clean CSS 

## Reference

* <https://getbootstrap.com/docs/5.1/components/modal/>
* <https://getbootstrap.com/docs/5.1/examples/>
* <https://getbootstrap.com/docs/5.1/examples/sign-in/>
* <https://getbootstrap.com/docs/5.1/examples/modals/>
* <https://firebase.google.com/>
* <https://codepen.io/romanfedosenko/pen/jYNEyo>
